var GC_CLIENT_ID='434919101138-4dot732ltjidfuq32loe9ukat94p0e2g.apps.googleusercontent.com';var GC_CLIENT_SECRET='Eh0ozftfR3b1Na-IPjhTQa47';var GC_API_KEY='AIzaSyCJvoTO69UArxaD_Gp1aK0JmDpPdGko81Q';(function($,Drupal,drupalSettings){function Calendar($container){this.$container=$container;this.$games=$('[data-game-date]');this.$container.datepicker({changeMonth:true,changeYear:true,yearRange:"2021:+2",dayNamesMin:[Drupal.t('Sunday'),Drupal.t('Monday'),Drupal.t('Tuesday'),Drupal.t('Wednesday'),Drupal.t('Thursday'),Drupal.t('Friday'),Drupal.t('Saturday')],monthNamesShort:[Drupal.t('January',{},{context:'Long month name'}),Drupal.t('February',{},{context:'Long month name'}),Drupal.t('March',{},{context:'Long month name'}),Drupal.t('April',{},{context:'Long month name'}),Drupal.t('May',{},{context:'Long month name'}),Drupal.t('June',{},{context:'Long month name'}),Drupal.t('July',{},{context:'Long month name'}),Drupal.t('August',{},{context:'Long month name'}),Drupal.t('September',{},{context:'Long month name'}),Drupal.t('October',{},{context:'Long month name'}),Drupal.t('November',{},{context:'Long month name'}),Drupal.t('December',{},{context:'Long month name'}),],firstDay:1,dateFormat:'dd.mm.yy',onChangeMonthYear:this.renderGames.bind(this)}).datepicker('setDate',this.$container.data('initial-date'));this.$container.find('.ui-datepicker-title > .ui-datepicker-month').addClass('custom__select');this.$container.find('.ui-datepicker-title > .ui-datepicker-year').addClass('custom__select');this.$container.on('click','td',this.handleDayClick.bind(this));this.$container.on('td > a').on('click',function(event){event.preventDefault();});this.renderGames();}
Calendar.prototype.handleDayClick=function(event){var date=$(event.currentTarget).find('[data-short-game-date]').data('short-game-date');if(date){$('[data-game-date="'+date+'"]').removeClass('d-none').css({top:window.scrollY});}};Calendar.prototype.renderGames=function(year,month){var date=new Date(this.$container.datepicker('getDate'));var currentMonth=month||date.getMonth()+1;var currentYear=year||date.getFullYear();setTimeout(function(){this.$container.find('td').off('click');this.replaceLastMonth(currentYear,currentMonth);this.replaceChooser();}.bind(this),0);this.$games.each(function(i,element){var $game=$(element);var gameDate=$game.data('game-date');var gameDateArr=$game.data('game-date').split('.');if(Number(gameDateArr[1])===currentMonth&&Number(gameDateArr[2])===currentYear){setTimeout(function(){var $day=this.getDayElement(gameDateArr);var $shortGame=$('[data-short-game-date="'+gameDate+'"]');$day.html('<span>'+$day.text()+'</span>'+$shortGame[0].outerHTML);}.bind(this),0);}}.bind(this));};Calendar.prototype.getDayElement=function(date){var $day=$();this.$container.find('.ui-state-default').each(function(i,element){if(Number(element.innerText)===Number(date[0])){$day=$(element);}}.bind(this));return $day;};Calendar.prototype.replaceLastMonth=function(year,month){var days=32-new Date(year,month-2,32).getDate();var $lastDays=this.$container.find('tbody tr').first().find('.ui-datepicker-other-month');$lastDays.each(function(i,element){$(element).html('<span>'+(days-$lastDays.length+i+1)+'</span>');});};Calendar.prototype.replaceChooser=function(){var $month=this.$container.find('.ui-datepicker-title > .ui-datepicker-month').addClass('custom__select');var $year=this.$container.find('.ui-datepicker-title > .ui-datepicker-year').addClass('custom__select');$month.wrap('<label></label>');$month.before('<span>'+Drupal.t('Month')+':</span>');$year.wrap('<label></label>');$year.before('<span>'+Drupal.t('Season')+':</span>');};function MobileCalendar($container){this.$container=$container;this.$month=$('.js-choose-month');this.$year=$('.js-choose-year');this.$games=$('[data-game-date]');this.$shortGames=$('[data-short-game-date]');this.$month.add(this.$year).off('change');this.$month.add(this.$year).on('change',this.renderSlider.bind(this));this.nothingToShowHTML=this.$container.html();this.$container.off('click');this.$container.on('click','[data-open-popup]',this.handleOpenPopup.bind(this));this.init();}
MobileCalendar.prototype.init=function(){if(this.$container.hasClass('init')){return;}
this.$container.addClass('init');this.nothingToShowHTML=this.$container.html();var currentDate=new Date();this.$month.find('[value="'+(currentDate.getMonth()+1)+'"]')[0].selected=true;this.$year.find('[value="'+currentDate.getFullYear()+'"]')[0].selected=true;this.renderSlider();};MobileCalendar.prototype.renderSlider=function(){var month=this.$month.val();var year=this.$year.val();var html='';this.$shortGames.each(function(i,element){var $element=$(element);if($element.data('short-game-date').indexOf(month+'.'+year)!==-1){html+=$element.html();}}.bind(this));if(!html){this.$container.html(this.nothingToShowHTML);return;}
setTimeout(function(){this.$container.html('<div class="js-calendar-carousel hockey-slider-container hockey-slider-container--secondary">'+'<div class="js-carousel-slider hockey-slider">'+html+'</div>'+'</div>');$(window).trigger('createCalendarCarousel');}.bind(this),0);};MobileCalendar.prototype.handleOpenPopup=function(event){var date=$(event.currentTarget).data('open-popup');if(date){$('[data-game-date="'+date+'"]').removeClass('d-none').css({top:window.scrollY});}};function GoogleCalendar($trigger){this.$trigger=$trigger;gapi.load('client:auth2',this.initClient.bind(this));}
GoogleCalendar.prototype.initClient=function(){gapi.client.init({apiKey:GC_API_KEY,clientId:GC_CLIENT_ID,discoveryDocs:['https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest'],scope:'https://www.googleapis.com/auth/calendar.events'}).then(this.init.bind(this),this.error.bind(this));};GoogleCalendar.prototype.init=function(){gapi.auth2.getAuthInstance().isSignedIn.listen(this.loadEvents.bind(this));this.loadEvents(gapi.auth2.getAuthInstance().isSignedIn.get());};GoogleCalendar.prototype.error=function(error){console.error(error.details);this.$trigger.addClass('btn--disabled').find('span').text('Error');};GoogleCalendar.prototype.loadEvents=function(isSignedIn){if(!isSignedIn){return gapi.auth2.getAuthInstance().signIn();}
$('[data-game-date]').each(function(i,element){var $element=$(element);var date=$element.data('game-date').split('.');var time=$element.find('.js-calendar-time').text();var title=$element.find('.js-calendar-title').text();var text=$element.find('.js-calendar-text').text();var location=$element.find('.js-calendar-location').text();var dateTime=new Date(date[1]+'.'+date[0]+'.'+date[2]+' '+time);var endDateTime=new Date(date[1]+'.'+date[0]+'.'+date[2]+' '+time);endDateTime=new Date(endDateTime.setHours(endDateTime.getHours()+1));if(dateTime.getTime()<new Date().getTime()){return;}
var request=gapi.client.calendar.events.insert({'calendarId':'primary','resource':{'summary':title,'location':location,'description':text,'start':{'dateTime':dateTime,'timeZone':'Europe/Riga'},'end':{'dateTime':endDateTime,'timeZone':'Europe/Riga'},'recurrence':['RRULE:FREQ=DAILY;COUNT=2'],'reminders':{'useDefault':false,'overrides':[{'method':'email','minutes':24*60},{'method':'popup','minutes':10}]}}});request.execute(function(event){this.$trigger.addClass('btn--disabled').find('span').text('Success');});});};Drupal.behaviors.iceHockey={attach:function attach(context,settings){$('.js-scroll-link',context).on('click',function(event){var $element=$($(event.currentTarget).attr('href'));if($element.length){event.preventDefault();$('body, html').animate({scrollTop:$element.offset().top-40},600);}});$('.js-hockey-video-open',context).on('click',function(event){event.preventDefault();var popupId=$(event.currentTarget).attr('href');var $popup=$(popupId);var videoUrl=$popup.data('video-url');var $frame=$popup.find('iframe');$popup.removeClass('d-none').css({top:window.scrollY});$frame.attr('src',videoUrl);$popup.one('click','.popup-close',function(){$frame.attr('src','');});});$('.js-hockey-form-open',context).on('click',function(event){var $currentSlide=$(event.currentTarget).closest('.hockey-slider__item');var $info=$currentSlide.find('.js-hockey-slide-info');var $form=$currentSlide.find('.js-hockey-slide-form');$form.removeClass('d-none').css('min-height',$info.height());$info.addClass('d-none');$form.find('.js-hockey-form-close').one('click',function(){$info.removeClass('d-none');$form.addClass('d-none');});});$('.js-hockey-form',context).on('submit',function(event){event.preventDefault();var $form=$(event.currentTarget);var $button=$form.find('.btn');var $inputs=$form.find('input, textarea, select').not('[type="submit"]');var $container=$form.closest('.js-hockey-slide-form');var $formContainer=$container.find('.js-hockey-slide-form-container');var $successContainer=$container.find('.js-hockey-slide-form-success');var $errorContainer=$container.find('.js-hockey-slide-form-error');var action=$form.attr('action');var method=$form.attr('method')||'post';var data=new FormData();$inputs.prop('disabled',true).each(function(i,element){var $element=$(element);data.append($element.attr('name'),$element.val());});$button.addClass('btn--disabled');$errorContainer.addClass('d-none');$.ajax({type:method,url:action,data:data,processData:false,contentType:false,success:handleRequestSuccess,error:handleRequestError});function handleRequestSuccess(data){$button.removeClass('btn--disabled');$inputs.prop('disabled',false);$formContainer.addClass('d-none');$successContainer.removeClass('d-none');$successContainer.find('.js-form-code').text('AASDEW');}
function handleRequestError(error){$button.removeClass('btn--disabled');$inputs.prop('disabled',false);$errorContainer.removeClass('d-none');}});$('.js-form-copy-code',context).on('click',function(event){event.preventDefault();var $button=$(event.currentTarget);var code=$button.siblings('.js-form-code').text();navigator.clipboard.writeText(code).then(function(){$button.text('Copied');}).catch(function(){});});var $calendarContainer=$('.js-calendar');var $calendarSliderContainer=$('.js-calendar-slider');if($calendarContainer.offset().top){new Calendar($calendarContainer);}
else{new MobileCalendar($calendarSliderContainer);}
$('.hockey-text__readmore__btn',context).on('click',function(event){event.preventDefault();$(event.currentTarget).addClass('d-none');$('.js-read-more-content').removeClass('hockey-text__readmore');});$('.js-google-calendar',context).on('click',function(event){new GoogleCalendar($(event.currentTarget));});}};})(jQuery,Drupal,drupalSettings);;
(function($,Drupal){Drupal.behaviors.videoGroupPopup={attach:function attach(context,settings){$('.js-group-video-open',context).on('click',function(event){event.preventDefault();var $elem=$(event.currentTarget);var popupId='#video-group-modal';var $popup=$(popupId);var videoUrl=$($elem.data('video-embed-popup')).find('iframe').attr('src');var $frame=$popup.find('iframe');$popup.removeClass('d-none').css({top:window.scrollY});$frame.attr('src',videoUrl);$popup.one('click','.popup-close',function(){$frame.attr('src','');});});}}})(jQuery,Drupal);;
(function(){function CustomEvent(event,params){params=params||{bubbles:false,cancelable:false,detail:undefined};var evt=document.createEvent('CustomEvent');evt.initCustomEvent(event,params.bubbles,params.cancelable,params.detail);return evt;}
CustomEvent.prototype=window.Event.prototype;window.CustomEvent=CustomEvent;})();(function(drupalSettings){'use strict';var iconSelectEvent=new CustomEvent('iconselectloaded');var xhr=new XMLHttpRequest();if(!drupalSettings.icon_select||!drupalSettings.icon_select.icon_select_url){return;}
xhr.open('get',drupalSettings.icon_select.icon_select_url,true);xhr.responseType='document';xhr.onreadystatechange=function(){if(xhr.readyState!==4){return;}
try{var svg=xhr.responseXML.documentElement;svg=document.importNode(svg,true);svg.id='svg-icon-sprite';document.body.appendChild(svg);svg.style.display='none';svg.style.display='block';}
catch(e){console.log(e);}
window.dispatchEvent(iconSelectEvent);};xhr.send();})(drupalSettings);;
(function($,Drupal){'use strict';jQuery.fn.putCursorAtEnd=function(){return this.each(function(){var $el=$(this),el=this;if(!$el.is(":focus")){$el.focus();}
if(el.setSelectionRange){var len=$el.val().length*2;setTimeout(function(){el.setSelectionRange(len,len);},1);}else{$el.val($el.val());}});};if($('.js-search-tab').length>0){$('.icon--search').closest('a').click();var searchField=$('#search form').find('input[type=\'text\']');searchField.putCursorAtEnd();}
var results=[];var searchString='';var submited=false;function showResults(result,settings){if(submited){return;}
var data='<div class="sticky-header__container">';if(result!==null&&result.length>0){$.each(result,function(index,value){data+='<div class="main-search-result__cell">';if(typeof value.href!='undefined'){data+='<a href='+value.href+' class="main-search-result__hd">'+value.name+' <span>'+value.total+'</span></a>';}
else{data+='<a class="main-search-result__hd">'+value.name+' <span>'+value.total+'</span></a>';}
if(value.total===0){data+='<div class="search-res-list__item">';data+=value.empty_text;}
else{data+='<div class="main-search-result__list">';}
if(value.data.length>0){if(value.display_type==='products'){data+='<div class="products-list">';$.each(value.data,function(link_index,link_value){data+=link_value.link;});data+='</div>';}
else if(value.display_type==='products_categories'){data+='<ul class="search-res-list _bold">';$.each(value.data,function(link_index,link_value){data+='<li class="search-res-list__item">';data+=link_value.link;data+='</li>';});data+='</ul>';}
else{data+='<ul class="search-res-list">';$.each(value.data,function(link_index,link_value){data+='<li class="search-res-list__item">';data+=link_value.link;data+='</li>';});data+='</ul>';}}
data+='</div>';if(typeof value.url!=='undefined'){data+=value.url;}
data+='</div>';});}else{data+='<div class="search-result__empty" style="display: block;"><p class="pink text-center">'+settings.bite_search.no_results_text+'</strong></p></div>';window.dataLayer=window.dataLayer||[];window.dataLayer.push({'event':'EmptySearch','keyword':searchString,});}
data+='</div>';$('.js-header-search-results').html(data);}
var loader=function(){var search_container=$('.sticky-header__container');if(search_container.find('.ajax-progress').length===0){var loader='<div class="ajax-progress loader is-active"> <div class="loader__content"> <div class="loader__child loader__child--1"></div><div class="loader__child loader__child--2"></div><div class="loader__child loader__child--3"></div></div></div>';search_container.append(loader);}}
Drupal.behaviors.biteSearch={attach:function(context,settings){$('.js-search-tab',context).click(function(){var href=$(this).data('href');if(typeof href!=='undefined'&&href!==''){loader();window.location.href=href;return false;}});$('.main-search__inp',context).on('paste keyup',function(){var val=$(this).val();val=$.trim(val);if(searchString===val){return;}
searchString=val;if(val.length>=settings.bite_search.min_length){if(typeof results[val]!=='undefined'){if(results[val]!==false){showResults(results[val],settings);}
return;}
results[val]=false;$.ajax({url:settings.bite_search.url,method:'GET',data:{'search':val},dataType:"json",success:function(response){if(typeof response.result!=='undefined'){results[val]=response.result;if(searchString===val){showResults(response.result,settings);}}}});}});}};})(jQuery,Drupal);;
